# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-16 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.RemoveField(
            model_name='surveydata',
            name='compass',
        ),
        migrations.RemoveField(
            model_name='surveydata',
            name='gz',
        ),
        migrations.RemoveField(
            model_name='surveydata',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='compass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='aoi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.AOI'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='canopy_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.CanopyStatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='crown_diameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.CrownDiameter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='tree_specie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.TreeSpecie'),
            preserve_default=False,
        ),
    ]
