# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-21 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190516_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydata',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
