# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-07 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190521_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicalzone',
            name='wms_url',
            field=models.TextField(),
        ),
    ]
